### ISSUE TITLE
Update repository files

### ISSUE THREAD

**Issue by itaymesh** [Magento2Translations/language_he_il#1]
Hi,
Can you tell me what's triggers the repo update? 
Thanks

**Comment by MrGekko** [comment]
Yeah sure, It is a cronjob on one of my servers. It runs once every day. Basically it is a shell script that updates all languages using https://github.com/Magento2Translations/Compile & crowdin

**Comment by itaymesh** [comment]
Great. If there is anything my team can help with, let me know.
