### ISSUE TITLE
question about creating a second translation file

### ISSUE THREAD

**Issue by hezide** [Magento2Translations/language_he_il#5]
Hi,
it's not an issue but a question.
Is it possible to create a new csv that will work simultaneously with the he_IL.csv file?
or maybe even be in a higher priority than he_IL.csv?

This is because sometimes I encounter new phrases that are not included in the he_IL.csv file but I want to stay synced with it.

thanks!

**Comment by MrGekko** [comment]
You could add them to a theme... they will overwrite the language packs

**Comment by hezide** [comment]
thank you!
